### ISSUE TITLE
git HEAD fails to build with due to system error

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2021]
While trying to build git HEAD -- sha `330bb2cfb`:
```
$ git clone ...racket
$ cd racket
$ make CONFIGURE_ARGS_qq='CFLAGS="-Og -Wall -g" --enable-gracket --enable-jit --enable-foreign --enable-places --enable-futures --enable-float --enable-racket=/home/pmatos/installs/racket-6.12/bin/racket --enable-backtrace --enable-pthread --disable-strip --enable-ubsan --enable-xonx' CPUS=16
...
make[9]: Entering directory '/home/pmatos/Projects/racket/racket/src/build/racket'
/home/pmatos/installs/racket-6.12/bin/racket -cu ../../racket/src/compile-startup.rkt cstartup.inc cstartup.zo ../../racket/src/startup.inc ../../racket/src/schvers.h
/home/pmatos/Projects/racket/racket/src/racket/src/compile-startup.rkt:87:28: compile-linklet: unbound identifier in module
  in: compile-linklet
  context...:
   standard-module-name-resolver
```

**Comment by pmatos** [comment]
OK, the problem seems to be related to `--enable-racket=/home/pmatos/installs/racket-6.12/bin/racket`

**Comment by pmatos** [comment]
Even if I leave out the `--enable-racket` option I still get:
```
make[7]: Leaving directory '/home/pmatos/Projects/racket/racket/src/build'
racket/racket3m -X "/home/pmatos/Projects/racket/racket/collects" -G "/home/pmatos/Projects/racket/racket/etc" -G /home/pmatos/Projects/racket/build/config  --no-user-path -N "raco" -l- setup --no-user -j 16  
raco setup: bootstrapping from source...
 triggered by use of non-".zo" file
  path: /home/pmatos/Projects/racket/racket/collects/compiler/private/cm-minimal.rkt
../../../racket/src/unwind/libunwind.c:2561:5: runtime error: null pointer passed as argument 2, which is declared to never be null
../../../racket/src/unwind/libunwind.c:2566:5: runtime error: null pointer passed as argument 2, which is declared to never be null
open-input-file: cannot open input file
  path: /home/pmatos/Projects/racket/racket/collects/setup/infotab/lang/reader.rkt
  system error: Structure needs cleaning; errno=117
  context...:
   default-load-handler
   standard-module-name-resolver
   syntax-local-module-exports
   /home/pmatos/Projects/racket/racket/collects/racket/require-transform.rkt:266:2: expand-import
   /home/pmatos/Projects/racket/racket/collects/racket/private/reqprov.rkt:439:5
   /home/pmatos/Projects/racket/racket/collects/racket/require-transform.rkt:266:2: expand-import
   /home/pmatos/Projects/racket/racket/collects/racket/private/reqprov.rkt:266:21: try-next
   /home/pmatos/Projects/racket/racket/collects/racket/private/reqprov.rkt:243:2: require
   apply-transformer-in-context
   dispatch-transformer
   do-local-expand56
   /home/pmatos/Projects/racket/racket/collects/syntax/wrap-modbeg.rkt:46:4: do-wrapping-module-begin
   apply-transformer-in-context
   dispatch-transformer
   loop
   finish
```

**Comment by mflatt** [comment]
I've pushed a repair to the ubsan-detected problem.

**Comment by pmatos** [comment]
I confirm the fix to the ubsan issue. The other problem persists.

**Comment by mflatt** [comment]
The problem with building Racket v6.90.x using Racket v6.12? That just can't work. Building Racket with Racket requires a sufficiently recent Racket.

**Comment by pmatos** [comment]
But I disabled the `--enable-racket` flag. Still have `racket` 6.12 in PATH. Is it the case that I need to download a pre-built snapshot to build this?

Still doesn't make sense as I ge the same issue if I try to build 6.12 tag.

**Comment by pmatos** [comment]
Ah... I thought `system error: Structure needs cleaning` error was from racket but it's actually a message saying my file system needs checking as it's corrupt. :(

**Comment by pmatos** [comment]
I can confirm the problem was disk corruption. Thanks. Closing this.
