### ISSUE TITLE
Inconsistencies Between Racket and RacketCS in Numeric Operations

### ISSUE THREAD

**Issue by stamourv** [racket/racket#2708]
Found by the (extended) TR random tester (then reduced).

- `(round -0.5)`
Racket: -0.0
RacketCS: 0.0

- `(sqrt -0.0)`
Racket: -0.0
RacketCS: 0.0+0.0i

- `(make-rectangular 0 1.0)`
`(sqrt -1.0)`
These produce complex numbers. Racket has exact 0 in the real part, RacketCS has 0.0.

- `(log -0.0)`
Off by pi error.
Racket: -inf.0
RacketCS: -inf.0+3.141592653589793i

- `(log (fllog -1.0))`
`(log (flsqrt -1.0))`
Also off by pi, but this time with NaN as the real part.

- `(/ 4.57240478624564e-205)`
Racket and RacketCS produce the same result, but print it in slightly different formats.
Racket: 2.1870329656904475e+204
RacketCS: 2.1870329656904475e204

- `(sin 2+1.0e-239i)`
`(sin -5.13387441043805+10.45469008713804i)`
`(sqrt -0.2775781188995694-1.7976931348623113e+308i)`
`(tanh 1-8.359869891121873e+136i)`
`(tan -1+0.32263741614737484i)`
`(expt (log -6.745235566427848e-195) (tanh 2.730216683980573e+81))`
Combining trig operations and complex numbers can produce slightly different float results.

- `(expt -19842562309 (exp 1))`
Slightly different float results, but also slightly different output format.

**Comment by pmatos** [comment]
Interesting work. Where does this TR random tester live?

**Comment by samth** [comment]
I tested the first 5 and the difference all shows up in regular Chez Scheme as well.

**Comment by stamourv** [comment]
@pmatos: https://github.com/racket/typed-racket/blob/master/typed-racket-test/tr-random-testing.rkt

**Comment by mflatt** [comment]
Some of these are related to failures in the core "number.rktl" suite. I hadn't noticed the output-format difference!

**Comment by mflatt** [comment]
I've pushed some repairs to `racket/ChezScheme`.

Chez Scheme doesn't have non-real numbers with an exact 0 real component, and that difference is likely to be permanent. Also, I didn't yet try to fix any differences in these examples that have to do with precision (especially with trig operations and complex numbers). The other problems should be fixed.

**Comment by gus-massa** [comment]
In the list of "known" differences, I have two to highlight:

    ((numbers) (0.7853981633974483+177.09910463306602i -inf.0 (#<procedure:atan> 0.0+1.0i)))
 
I still don't understand how it makes sense. (But I'm too lazy to make a complete analysis of the complex branches of  `atan`)

    ((numbers) (("1.631463146314631464") Error (number->string 1.8 8)))

It's a feature, not a bug. But porting to the traditional implementation the correct amount of rounding may be a difficult.

**Comment by mflatt** [comment]
The `atan` and `number->string` differences are now fixed, along with other failures in the core test suite. Mostly, the repairs were to Racket (as opposed to Chez Scheme or Racket CS).

Where there are still precision differences between Racket and Racket CS, Racket CS seems better. That's especially clear for `(sqrt -0.2775781188995694-1.7976931348623113e+308i)`, where Racket CS avoids overflow and Racket doesn't. In other cases, Racket CS seems to agree better with Gambit, whose numerics I trust more than most.

I found some corners to improve in Chez Scheme while aligning Racket and Racket CS for the core Racket test suite, so it's probably worth running at least one more round of random-driven comparison.

**Comment by stamourv** [comment]
The tester is running on drdr: http://drdr.racket-lang.org/52378/racket/share/pkgs/typed-racket-test/tr-random-testing.rkt

Some of the failure it reports are things we already know about (e.g., complexes with exact 0 real part), though.

Also, only the first few counterexamples it finds are going to be useful. Looks like sometimes, after a certain number of tests, all tests start failing. I'll have to look into that.

**Comment by samth** [comment]
I've added another case where they differ by sign, and tracked the current status in the issue.
