### ISSUE TITLE
8.1 package regressions

### ISSUE THREAD

**Issue by samth** [racket/racket#3779]
### Build Failures
- [x] satore https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/satore.txt (two files that differ only in case causes problems when archiving on Mac)
- [x] trustyou https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/trustyou.txt (package removed)

#### Timeouts
- [x] gtp-plot https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/gtp-plot.txt
- [x] nanopass https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/nanopass.txt
- [x] ralist https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/ralist.txt
- [x] bv https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/bv.txt
#### Other test failures
- [x] delay-pure https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/delay-pure.txt (maybe related to Typed Racket struct changes)
- [x] rml-decisiontrees https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/rml-decisiontrees.txt (previously seen timeout in tests)

**Comment by samth** [comment]
`satore` seems fine when I try to install it.

**Comment by mfelleisen** [comment]
I asked Leif to check into nanopass.

**Comment by samth** [comment]
There's not really an issue with nanopass, just different performance on the two machines.

**Comment by rfindler** [comment]
> There's not really an issue with nanopass, just different performance on the two machines.

Would a larger timeout somewhere help? Or is that not the issue?

**Comment by samth** [comment]
Increasing the 90 second timeout for tests would maybe fix those three failures. Last time we talked about this there wasn't a configuration in pkg-build for setting that timeout, I think.

**Comment by mflatt** [comment]
@samth I think this is a simplification of the `phc-toolkit/untyped` issue:
```
#lang typed/racket
(struct g ())
(struct A2 g () #:type-name A)
```

By making it a little more complex with a macro, you get more the same error as the pkg-build failure:

```
#lang typed/racket

(define-syntax (define-logn-ids stx)
  (syntax-case stx ()
    [(_ A)
     (with-syntax ([(g A2) (generate-temporaries #'(g A))])
       #`(begin
           (struct g ())
           (struct A2 g () #:type-name A)))]))

(define-logn-ids A)
```

**Comment by samth** [comment]
cc @capfredf

**Comment by samth** [comment]
This should be fixed by racket/typed-racket#1069

**Comment by samth** [comment]
Looks like the first four errors are possibly also related to recent Typed Racket struct changes.

**Comment by samth** [comment]
I think the problem with `satore` is about case-sensitive file systems. @rfindler is the NW pkg-build on a case-sensitive system?

**Comment by rfindler** [comment]
The host running the pkg build is a case-preserving but case-insensitive filesystem (mac os). I'm not sure what's the situation with the VMs but probably just case-sensitive.

**Comment by samth** [comment]
I am confused about how it could be going wrong otherwise, but I have only tested on Linux.

**Comment by samth** [comment]
Looking more at the `trustyou` failure, I don't understand what's going on there. Maybe @mflatt has some suggestions for what to look into?

@capfredf can you look at the `delay-pure` failure?

Other than `delay-pure`, all of the problems seems to be internal to the pkg build system.

**Comment by mflatt** [comment]
I think the problem with `trustyou` is just that the repo no longer exists on GitHub, so the pkg-build catalog doesn't refer to a local copy and instead refers to the GitHub URL (which fails trying to access github.com).

**Comment by samth** [comment]
@jsmaniac Can you look at the issue with `delay-pure`? I'm having trouble understanding all of the `eval` indirections here. My guess is that it's expecting this to work:

```
(struct m () #:constructor-name make-m)
(m)
```

but it doesn't. It may have previously erroneously worked but we want to make things align with `#lang racket` where this does not work.

**Comment by capfredf** [comment]
@jsmaniac After an initial investigation and attempt to fix delay-pure, my understanding is 
1. as @smath mentioned, the code relies on the implementation of Typed Racket's structure types, especially the representation of exported structure related names, which could be potentially problematic.
2. immutable-struct-constructor?'s needs to be changed, not only because TR's implementation has changed, but also because it assumes a structure's struct-info can be obtained from its constructor when the constructor name is different from the structure name.  To my knowledge, I don't think that is possible (maybe @mflatt knows)

But thanks to your code, I found a potential bug in TR.

**Comment by Metaxal** [comment]
For satore, I can change the name of the file if it's too bothering on your side.

That said, it's not exactly straightforward for me either because there's a complicated process to push things onto this repo which I don't own, but maybe I'll just 'clone' it. Well, I also can't exactly clone it directly on github because it's a subdirectory of a repository, which means I need to clone the whole repo. But at least that would also help with downloading it, because I believe `raco pkg install satore` currently also downloads the whole repo archive and then extracts only the corresponding subdirectory, doesn't it? As this repository is likely going to grow in size over time, this will only make things worse.

**Comment by bennn** [comment]
I've changed `gtp-plot` to skip a long-running test when `CI=true`

**Comment by gus-massa** [comment]
About satore: Can it be a lowercase/uppercase difference in the name?

    raco setup:     path: /home/root/user/.local/share/racket/snapshot/pkgs/satore/clause.rkt
                                                                                   ^
    raco setup:     system error: no such file or directory; rkt_err=3
    raco setup:     compiling: <pkgs>/satore/tests/Clause.rkt
                                                   ^

**Comment by samth** [comment]
@gus-massa yes, that's the problem (although the fact that both of them appear in the error is a coincidence). Because there are two files with the same name modulo case, the package archiving process (which happens on a Mac for the nightly pkg-build) loses one file, which happens to be the uppercase one. 

Fundamentally, packages that rely on this working can't be portable to most Macs, and thus need to change. I think @Metaxal is the one to do that.

**Comment by Metaxal** [comment]
Ok, I'll try to do something about it. Is it blocking for someone/something, and if so is there a particular deadline by which this should be fixed?

**Comment by samth** [comment]
No, this isn't blocking anything (and it will continue to work on pkg-build.racket-lang.org after 8.1, the problem is specific to the setup for the nightly pkg-build). The only problem is for you -- you can't discover other potential build failures on snapshots until this is fixed.

**Comment by jsmaniac** [comment]
I recently tried bringing most of my packages to a "green" state on pkgs.racket-lang.org and travis-ci, is `delay-pure` still having issues?

**Comment by samth** [comment]
@jsmaniac I believe we changed Typed Racket in a way that caused `delay-pure` to work again. However, I think the approach that `delay-pure` takes to handling structs is inherently fragile and likely to break.

**Comment by Metaxal** [comment]
`satore` is fixed (basically by dirty-cloning the original subrepo and fixing things locally)

**Comment by jbclements** [comment]
Okay, looks to me like this issue can be closed. Thanks!
